apiVersion: v2
description: A Helm chart for CM Kubernetes
name: cm-aws-ebs-csi-driver
version: 0.0.0

dependencies:
- name: aws-ebs-csi-driver
  version: 2.52.1
  repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
